apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
  namespace: default
  
data:
    API_KEY: "A6E11D2B-3F3E-492D-A18F-78DF7EFE576B"
    CACHE_TIME: "300"
    CURRENCY_NAME: "btc"
    SERVER_PORT: "5000"
