apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-server
  name: my-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-server
    spec:
      containers:
      - image: mohadesehatyabi/step2
        imagePullPolicy: IfNotPresent
        name: step2
        resources: {}
        env:
        - name: API_KEY
          valueFrom:
            configMapKeyRef:
              name: server-config
              key: API_KEY
        - name: CACHE_TIME
          valueFrom:
            configMapKeyRef:
              name: server-config
              key: CACHE_TIME
        - name: CURRENCY_NAME
          valueFrom:
            configMapKeyRef:
              name: server-config
              key: CURRENCY_NAME
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: server-config
              key: SERVER_PORT
        ports:
          - containerPort: 5000
        volumeMounts:
          - mountPath: ./server-config.config
            subPath: server-config.config
            name: config-map
            readOnly: true
      volumes:
        - name: config-map
          configMap:
            name: server-config
status: {}